import { companyInfo, destinations, properties } from '../data.js';
import copy from './compactCopy.json';

const escape = value => String(value).replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
const paragraphs = text => text.split('\n\n').map(p => `<p>${escape(p)}</p>`).join('');
const action = (route, label) => `<a class="compact-button" href="#${route}" data-route="${route}">${label} <span aria-hidden="true">○</span></a>`;
const section = (title, body, className = '') => `<section class="compact-section ${className}"><h2>${title}</h2>${body}</section>`;
const propertyCards = items => `<div class="compact-grid">${items.map(p => `<a class="compact-property" href="#property?id=${p.id}" data-route="property" data-id="${p.id}"><img src="${p.image}" alt="${p.title}" loading="lazy"><div><small>${p.badge}</small><h3>${p.title}</h3><p>${p.location}</p><p>${p.bedrooms} Beds · ${p.bathrooms} Baths · ${p.area}</p><strong>${p.price}</strong></div></a>`).join('')}</div>`;
const testimonials = () => section('What Our Clients Say About Us', `<div class="compact-grid">${['Hillary Watson', 'Sara Azarmnia', 'James Levante'].map((name, i) => `<blockquote><span class="compact-stars" aria-label="5 stars">★★★★★</span>${paragraphs(copy[`testimonial${i + 1}`])}<cite>${name}</cite></blockquote>`).join('')}</div>`, 'compact-testimonials');
const consultation = () => section('Guidance Built for Overseas Buyers', action('contact', 'Book A Consultation'), 'compact-muted');

// Reflow the existing design's copy and assets only at the compact breakpoint.
// The original desktop stage remains in place, including its precise overlays.
export function renderCompactSections(page, params = {}) {
  const destination = destinations.find(d => d.id === params.country) || destinations[0];
  const about = section('About Asili', paragraphs(copy.about) + (page === 'home' ? action('about', 'Learn More') : ''), 'compact-about');
  const journal = section('News & Blog', '<p>Stay updated with the latest real estate trends, investment tips, and market analysis.</p>' + action('news', 'News & Blogs'), 'compact-journal');
  let content = '';
  if (page === 'home') {
    content = about + section('Why Choose Asili Holding', '<p>We combine local expertise with international standards to deliver exceptional property solutions and lasting value.</p><div class="compact-grid"><article><h3>Global Expertise</h3><p>Over $18M in international property sales.</p></article><article><h3>Client-Centric Approach</h3><p>Personalized solutions for investors &amp; homeowners.</p></article><article><h3>Market Intelligence</h3><p>Data-driven strategies for high-yield investments.</p></article><article><h3>End-to-End Services</h3><p>Covering everything from property acquisition to construction.</p></article></div><div class="compact-actions">' + action('listings', 'Property Search') + action('contact', 'Book A Consultation') + '</div>', 'compact-why compact-muted') + testimonials() + section('Explore Our Collection of Exclusive Real Estate Deals', paragraphs(copy.deals) + propertyCards(properties.slice(0, 2)) + action('listings', 'Property Search'), 'compact-muted') + journal;
  } else if (page === 'about') {
    content = about + section('Our History', paragraphs(copy.history), 'compact-history') + section('Our CEO', '<img class="compact-editorial" src="/assets/Vector_14-2003_2467.png" alt="Cyrus Asili" loading="lazy">' + paragraphs(copy.ceo), 'compact-ceo compact-muted') + section('Our Gallery', `<div class="compact-grid">${[2502,2503,2504,2505,2506].map(id => `<img class="compact-editorial" src="/assets/Vector-2003_${id}.png" alt="ASILI company event" loading="lazy">`).join('')}</div>` + action('gallery', 'View Gallery')) + journal;
  } else if (page === 'listings') {
    content = section('Property Marketplace', '<p class="compact-result-count" aria-live="polite"></p><div class="compact-results"></div>', 'compact-listings') + section('Can’t Find the Right Fit?', action('contact', 'Book A Consultation'), 'compact-muted') + journal;
  } else if (page === 'services') {
    content = section('Market Snapshot', `<nav class="compact-actions" aria-label="Investment destinations">${destinations.map(d => `<a class="compact-button" href="#services?country=${d.id}" data-route="services" data-country="${d.id}" ${d.id === destination.id ? 'aria-current="page"' : ''}>${d.name}</a>`).join('')}</nav><div class="compact-table" role="region" aria-label="Market snapshot" tabindex="0"><table><thead><tr><th>City / Area</th><th>Entry Price</th><th>Rental Yield</th><th>Growth Outlook</th></tr></thead><tbody>${destination.cities.map(c => `<tr><td>${c.name}</td><td>${c.price}</td><td>${c.yield}</td><td>${c.outlook}</td></tr>`).join('')}</tbody></table></div><p>Indicative figures based on existing ASILI listings. Speak to our team for a live, property-specific breakdown.</p>`) + section('A Market Built on Stability', `<img class="compact-editorial" src="${destination.heroImage}" alt="${destination.name}" loading="lazy"><p>${destination.description}</p>`, 'compact-muted') + section(`${destination.name} Properties We’re Currently Representing`, propertyCards(properties.filter(p => p.country === destination.id)) + `<a class="compact-button" href="#listings?country=${destination.id}" data-route="listings" data-country="${destination.id}">View All Listings</a>`) + consultation() + testimonials() + journal;
  } else if (page === 'contact') {
    content = section('Get in Touch', `<div class="compact-grid"><article><h3>Call Us</h3><a href="tel:+442075808490">${companyInfo.phones[0]}</a><br><a href="tel:+447811441111">${companyInfo.phones[1]}</a></article><article><h3>Email Us</h3><a href="mailto:${companyInfo.email}">${companyInfo.email}</a><br><a href="mailto:${companyInfo.salesEmail}">${companyInfo.salesEmail}</a></article><article><h3>Visit Us</h3><p>${companyInfo.address}</p></article><article><h3>Office Hours</h3><p>${companyInfo.hours}</p></article></div><button type="button" class="compact-button" onclick="window.openBookingModal()">Book A Consultation</button>`, 'compact-muted') + section('A Market Built on Stability', `<img class="compact-editorial" src="${destinations.find(d => d.id === 'cyprus').heroImage}" alt="Cyprus" loading="lazy">`) + section('Cyprus Properties We’re Currently Representing', propertyCards(properties.filter(p => p.country === 'cyprus'))) + testimonials() + journal;
  }
  return `<div class="compact-content">${content}</div><footer class="compact-footer"><img src="/assets/ASILI_Holding_Long_Logo_WHT_Hollow_1-2003_1620.png" alt="ASILI Holding" width="150"><div><h2>Quick Links</h2><nav aria-label="Footer navigation">${[['home','Home'],['about','About Us'],['listings','Property Marketplace'],['services','Services'],['gallery','Gallery'],['news','News & Blogs'],['contact','Contact'],['privacy','Privacy Policy'],['terms','Terms & Conditions']].map(([route, label]) => `<a href="#${route}" data-route="${route}">${label}</a>`).join('')}</nav></div><div><h2>Contact Us</h2><a href="tel:+442075808490">${companyInfo.phones[0]}</a><a href="mailto:${companyInfo.email}">${companyInfo.email}</a><p>${companyInfo.address}</p></div><p class="compact-copyright">Copyright © 2026. Asili Holding Ltd. All rights reserved.</p></footer>`;
}

